# Generated by Django 3.1.5 on 2021-02-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.talk')),
            ],
        ),
    ]
