# Generated by Django 3.1.5 on 2021-02-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
