# Generated by Django 3.1.5 on 2021-02-06 09:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=200)),
                ('img_url', models.FileField(null=True, upload_to='')),
                ('category', models.CharField(max_length=200, null=True)),
                ('board_text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('lecture_title1', models.CharField(max_length=200, null=True)),
                ('lecture_video1', models.CharField(max_length=700, null=True)),
                ('lecture_title2', models.CharField(max_length=200, null=True)),
                ('lecture_video2', models.CharField(max_length=700, null=True)),
                ('lecture_title3', models.CharField(max_length=200, null=True)),
                ('lecture_video3', models.CharField(max_length=700, null=True)),
                ('lecture_title4', models.CharField(max_length=200, null=True)),
                ('lecture_video4', models.CharField(max_length=700, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200, null=True)),
                ('rate', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.mytext')),
            ],
        ),
    ]
