# Generated by Django 3.1.5 on 2021-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytext',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_title2',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_title3',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_title4',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_video2',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_video3',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_video4',
        ),
    ]
