# Generated by Django 3.1.5 on 2021-02-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20210206_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_title1',
        ),
        migrations.RemoveField(
            model_name='mytext',
            name='lecture_video1',
        ),
    ]
