# Generated by Django 3.1.5 on 2021-04-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20210303_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lecture',
            new_name='posting',
        ),
    ]
